- name: package installation on hosts
  hosts: all
  become: yes
  tasks:
    - name: install apache2
      ansible.builtin.package:
        name: apache2
        state: latest
    - name: start service apache, if not started
      ansible.builtin.package:
        name: apache2
        state: started
    - name: enabling the apache service and not touching the state
      ansible.builtin.package:
        name: apache2
        enabled: yes
        
        
    