- name: package installation on hosts
  hosts: all
  become: yes
  tasks:
    - name: install apache
      ansible.builtin.package:
        name: apache2
        state: latest
    - name: remove package
      ansible.builtin.package:
        name: nginx
        state: absent

        
        
    