- name: package installation on hosts
  hosts: all
  become: yes
  tasks:
    - name: install apache
      ansible.builtin.package:
        name:
          - nginx
          - apache2
        state: present
    - name: remove packages
      ansible.builtin.package:
        name:
          - nginx
          - apache2
        state: absent