- name: package installation on hosts
  hosts: all
  become: yes
  tasks:
    - name: install apache2
      ansible.builtin.package:
        name: apache2
        state: latest
    - name: enabling the apache service and not touching the state
      ansible.builtin.package:
        name: apache2
        enabled: yes
        
        
    