- name: install package on hosts
  hosts: all
  become: yes
  tasks:
    - name: install httpd 
      ansible.builtin.package:
        name:
          - apache2
          - nginx
      state: present

